name: ClusterFuzzLite batch fuzzing
on:
  push:
    branches:
      - main  # Use your actual default branch here.
  workflow_dispatch:
  schedule:
    - cron: '0 0/6 * * *'  # Every 6th hour. Change this to whatever is suitable.
permissions: read-all
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        #uses: google/oss-fuzz/infra/cifuzz/external-actions/build_fuzzers@artifact-per-target
      env:
        CIFUZZ_DEBUG: ''
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sanitizer: ${{ matrix.sanitizer }}
    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
        #uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      uses: google/oss-fuzz/infra/cifuzz/external-actions/run_fuzzers@batch-random
      env:
        CIFUZZ_DEBUG: ''
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 3600
        mode: 'batch'
        storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/oliverchang/cifuzz-external-storage.git
        sanitizer: ${{ matrix.sanitizer }}
