name: CIFuzz
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   steps:
   - name: echo env vars
     run: echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_BASE_REF $GITHUB_BASE_REF GITHUB_REF $GITHUB_REF GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_ACTION_REF $GITHUB_ACTION_REF GITHUB_SHA $GITHUB_SHA"
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@oss-fuzz-project-name-optional
     with:
       build-integration-path: 'fuzzer-build-integration'
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@oss-fuzz-project-name-optional
     with:
       fuzz-seconds: 600
   - name: Upload Crash
     uses: actions/upload-artifact@v1
     if: failure() && steps.build.outcome == 'success'
     with:
       name: artifacts
       path: ./out/artifacts

 BatchFuzzing:
   runs-on: ubuntu-latest
   steps:
   - name: echo env vars
     run: echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_BASE_REF $GITHUB_BASE_REF GITHUB_REF $GITHUB_REF GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_ACTION_REF $GITHUB_ACTION_REF GITHUB_SHA $GITHUB_SHA GITHUB_RUN_ID $GITHUB_RUN_ID"
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@oss-fuzz-project-name-optional
     with:
       build-integration-path: 'fuzzer-build-integration'
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@oss-fuzz-project-name-optional
     with:
       fuzz-seconds: 600
       github-token: ${{ secrets.GITHUB_TOKEN }}
       run-fuzzers-mode: 'batch'
